# Generated by Django 2.0.4 on 2018-04-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank='True', default='default.png', upload_to=''),
        ),
    ]
